# Generated by Django 4.1.7 on 2023-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مکان'),
        ),
    ]
