# Generated by Django 4.1.7 on 2023-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author_profile', '0003_alter_profile_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(max_length=700, verbose_name='اطلاعات'),
        ),
    ]
