# Generated by Django 4.1.7 on 2023-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_message_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactInfo', models.TextField(blank=True, null=True, verbose_name='توضیحات راه های ارتباطی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('phone', models.IntegerField(blank=True, max_length=12, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
            },
        ),
    ]
