# Generated by Django 4.1.7 on 2023-04-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactway',
            name='phone',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='شماره تماس'),
        ),
    ]
