# Generated by Django 4.1.7 on 2023-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_media', '0002_alter_image_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='حجم کمتر فیلم و فرمت mp4 به نمایش بهتر آن کمک میکند', upload_to='video/projects'),
        ),
    ]
