# Generated by Django 4.1.7 on 2023-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articleimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='article',
            name='image1',
            field=models.ImageField(default=1, upload_to='article/image', verbose_name='عکس 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='article/image', verbose_name='عکس2'),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='article/image', verbose_name='عکس3'),
        ),
        migrations.DeleteModel(
            name='ArticleImages',
        ),
    ]
