# Generated by Django 4.1.7 on 2023-04-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='درباه من')),
                ('image', models.ImageField(upload_to='image/about', verbose_name='عکس')),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درباره من',
            },
        ),
    ]
