# Generated by Django 4.1.7 on 2023-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
    ]
